### ISSUE TITLE
Forward/back buttons dont change the page

### ISSUE THREAD

**Issue by popey456963** [Miodec/monkeytype#667]
Sometimes I want to open things in new tabs (e.g. leaderboard), but at the moment I'm unable to.

**Comment by PickleTicklewithnospace** [comment]
You can't open any of the routes (e.g. `https://monkeytype.com/settings`) in a new tab without manually copying the url into a new tab and using the forward/back buttons on the browser won't return you to the previous route properly. Super annoying

**Comment by Miodec** [comment]
Opening in a new tab wouldn't work well since this is a single page application, but forward and back is something that should be fixed

**Comment by PickleTicklewithnospace** [comment]
Gmail is a prime example of a SPA and it does enable opening emails in a new tab using control + click. It can and does work extremely well in SPAs where it's appropriate.

**Comment by kungpaogao** [comment]
I was playing around with the source, and a relatively simple way to make middle (or ctrl) click and navigation work is just change the `<div>` tags to `<a>` tags. Then the browser will recognize them as links and handle them normally. 

The biggest issue is that the current navigation/routing (I think) makes it so that the browser navigates twice. I'm not really sure what's causing this to happen because I don't understand gulp. For example:
1. start at home page
2. (normal) click to go to about page
3. the browser will first navigate to `/about` like it currently does
4. then, it will navigate to `/about` again

There are a couple of other "caveats" too:
- you can click on the same link multiple times - I'm not super familiar with gulp, so maybe there's a way to detect current page and prevent that
- opening settings and modifying them in a separate tab doesn't update the original tab
- leaderboard is in a modal, so it's not really a separate page
- need to add some custom styling to remove link underlines - should be simple enough with some CSS

That's all I noticed for now.

**Comment by CameronCT** [comment]
Just curious, is anyone still having this problem right now? Unable to replicate locally and remotely.
